import { Component, defineComponent, h, PropType } from "vue";
import {
    ChevronDown,
    ChevronRight,
    ChevronUp,
    CircleChevronDown,
    CircleChevronRight,
    Download,
    Eye,
    EyeOff,
    FileCode2,
    House,
    Layers3,
    LogOut,
    Pause,
    Palette,
    Pencil,
    Play,
    Plus,
    RefreshCw,
    Rocket,
    RotateCw,
    Save,
    Search,
    Settings,
    ShieldCheck,
    Square,
    SquarePen,
    SquareTerminal,
    Trash2,
    X,
} from "@lucide/vue";

const icons: Record<string, Component> = {
    "angle-down": ChevronDown,
    "arrows-rotate": RefreshCw,
    "chevron-circle-down": CircleChevronDown,
    "chevron-circle-right": CircleChevronRight,
    "chevron-down": ChevronDown,
    "chevron-right": ChevronRight,
    "chevron-up": ChevronUp,
    "cloud-arrow-down": Download,
    cog: Settings,
    edit: SquarePen,
    eye: Eye,
    "eye-slash": EyeOff,
    home: House,
    pause: Pause,
    pen: Pencil,
    "pen-to-square": SquarePen,
    play: Play,
    plus: Plus,
    rocket: Rocket,
    rotate: RotateCw,
    save: Save,
    search: Search,
    "sign-out-alt": LogOut,
    stop: Square,
    terminal: SquareTerminal,
    times: X,
    trash: Trash2,
    warehouse: Layers3,
    palette: Palette,
    security: ShieldCheck,
    "file-code": FileCode2,
};

const sizes = {
    sm: 14,
    md: 18,
    lg: 22,
};

export const AppIcon = defineComponent({
    name: "AppIcon",
    inheritAttrs: false,
    props: {
        icon: {
            type: String,
            required: true,
        },
        size: {
            type: String as PropType<keyof typeof sizes>,
            default: "md",
        },
    },
    setup(props, { attrs }) {
        return () => h(icons[props.icon] ?? Square, {
            ...attrs,
            class: [ "app-icon", attrs.class ],
            size: sizes[props.size],
            strokeWidth: 2,
            "aria-hidden": "true",
        });
    },
});
